pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - pwd
    - rm -rf /srv/tobiaskolb.dev/*
    - yarn add webpack-cli
    - yarn
    - yarn run build
    - cp -R ./dist/* /srv/tobiaskolb.dev/
  only:
    - master